# Generated by Django 3.2.5 on 2021-07-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marketing',
            new_name='Another',
        ),
        migrations.RenameField(
            model_name='another',
            old_name='Tittle',
            new_name='descp',
        ),
        migrations.RenameField(
            model_name='another',
            old_name='subtitle',
            new_name='tittle',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='Tittle',
            new_name='descp',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='imagefield',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='subtitle',
            new_name='tittle',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='Tittle',
            new_name='descp',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='imagefield',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='subtitle',
            new_name='tittle',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button_url',
        ),
    ]
