# Generated by Django 3.2.5 on 2021-07-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_auto_20210713_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='another',
            old_name='imagefield',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='another',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='tittle',
            new_name='title',
        ),
    ]
